apiVersion: v1
data:
  ca-crl.pem: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-13T17:44:18Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca-crl.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2026-04-13T17:44:18Z"
  name: istio-ca-crl
  namespace: higress-system
  resourceVersion: "1"
