apiVersion: v1
data:
  adminDisplayName: YWRtaW4=
  adminPassword: MTIzNDU2
  adminUsername: YWRtaW4=
  iv: fXE+e0lhV1heNGZEMUAjVg==
  key: NXc2QTJSOWNKMGg8PmlYIz9JZG00RE5jUVI6KmlmSjI=
kind: Secret
metadata:
  creationTimestamp: "2000-01-01T00:00:00Z"
  labels:
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:adminDisplayName: {}
        f:adminPassword: {}
        f:adminUsername: {}
        f:iv: {}
        f:key: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-04-13T17:44:33Z"
  name: higress-console
  namespace: higress-system
  resourceVersion: "2"
type: Opaque
