apiVersion: v1
data:
  nacosPassword: bmFjb3M=
  nacosUsername: bmFjb3M=
kind: Secret
metadata:
  creationTimestamp: "2026-04-13T16:14:26Z"
  labels:
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:nacosPassword: {}
        f:nacosUsername: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-04-13T16:14:26Z"
  name: mcp-register-auth-s7g0j
  namespace: higress-system
  resourceVersion: "1"
